ARG version=8

FROM centos:${version}

RUN yum install -y xinetd sudo

# create /docker-entrypoint.sh
RUN echo -e \
"#!/bin/bash\n\
xinetd -dontfork -stayalive"\
> /docker-entrypoint.sh

RUN useradd ansible && \
    usermod -aG wheel ansible && \
    sed -i -e 's/^%wheel/#%wheel/' -e 's/^# %wheel/%wheel/' /etc/sudoers && \
    chmod 777 docker-entrypoint.sh

EXPOSE 6556/tcp

ENTRYPOINT ["/docker-entrypoint.sh"]
